### ISSUE TITLE
perspective view

### ISSUE THREAD

**Issue by anatolysukhanov** [anatolysukhanov/dnv#7]
For what its worth, I really liked that overhead shot from google that you used on woods drive
I think this perspective would be helpful in the dashboard
I think adding in the google imagery when reviewing parcels would be great next

its a specific site in the District of North Vancouver that has townhouses (older). I wanted to see how it appeared after your magic going back to the "next challenge". Assume 150 townhouse sites identified. Identfying whether there are improvements on the site already. What are they? perhaps with a dashboard it could bring up a google map with visuals

**Comment by anatolysukhanov** [comment]
The over head view is perfect

![Pasted File at December 24, 2020 4_38 AM](https://user-images.githubusercontent.com/7021042/103918463-e43d7100-511f-11eb-8734-960afbcd1ebc.png)

**Comment by anatolysukhanov** [comment]
https://developers.google.com/maps/documentation/javascript/examples/aerial-simple
https://developers.google.com/maps/documentation/javascript/examples/streetview-simple

**Comment by davewolstenholme** [comment]
higher priority

**Comment by anatolysukhanov** [comment]
> For what its worth, I really liked that overhead shot from google that you used on woods drive
I think this perspective would be helpful in the dashboard
I think adding in the google imagery when reviewing parcels would be great next

Google Maps offers fewer options programmatically (using their API). It supports 45° imagery providing perspective views towards each of the cardinal direction (https://developers.google.com/maps/documentation/javascript/maptypes#45DegreeImagery) for certain locations including Vancouver:

![image](https://user-images.githubusercontent.com/7021042/104124866-41296900-5364-11eb-8282-dd9af27b6b0f.png)

![image](https://user-images.githubusercontent.com/7021042/104124874-4d152b00-5364-11eb-8b4a-7925ab61a61e.png)

There is the rotate control in the left bottom corner:

![image](https://user-images.githubusercontent.com/7021042/104124970-f1976d00-5364-11eb-9a0f-00dbb5e4fdfb.png)

@davewolstenholme, please have a look at https://anatolysukhanov.com/dnv/

**Comment by anatolysukhanov** [comment]
Done.
